[workspace]
members  = [ "watt", "xtask" ]
resolver = "3"

[workspace.package]
authors      = [ "NotAShelf <raf@notashelf.dev>", "RGBCube <git@rgbcu.be>" ]
description  = "Modern CPU frequency and power management utility for Linux"
edition      = "2024"                                                        # Keep in sync with .rustfmt.toml.
license      = "MPL-2.0"
readme       = true
repository   = "https://github.com/notashelf/watt"
rust-version = "1.88"
version      = "1.0.0"

[workspace.dependencies]
anyhow                = "1.0.100"
clap                  = { features = [ "derive", "env" ], version = "4.5.50" }
clap-verbosity-flag   = "3.0.4"
clap_complete         = "4.5.59"
clap_complete_nushell = "4.5.9"
ctrlc                 = "3.5.1"
derive_more           = { features = [ "full" ], version = "2.0.1" }
env_logger            = "0.11.8"
log                   = "0.4.28"
nix                   = { features = [ "fs" ], version = "0.31.1" }
num_cpus              = "1.17.0"
serde                 = { features = [ "derive" ], version = "1.0.228" }
thiserror             = "2.0.17"
toml                  = "0.9.8"
yansi                 = { features = [ "detect-env", "detect-tty" ], version = "1.0.1" }
